version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: instatasks-app
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
      - redis
    networks:
      - laravel
    command: php-fpm

  nginx:
    image: nginx:stable-alpine
    container_name: instatasks-nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  mysql:
    image: mysql:8
    container_name: instatasks-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: instatasks
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel

  redis:
    image: redis:alpine
    container_name: instatasks-redis
    ports:
      - "6379:6379"
    networks:
      - laravel

volumes:
  db_data:

networks:
  laravel:
